.test_template: &test_definition
  stage: test
  tags:
    - docker
  script:
    - pip3 install -r requirements.txt || pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt || pip3 install -r requirements-dev.txt
    - pycodestyle .
    - python3 -c "import nltk; nltk.download('cmudict')"
    - pytest tests --cov=hyphenator --cov-report term --cov-report html

test_python3.7:
  image: python:3.7
  <<: *test_definition

test:
  image: python
  <<: *test_definition
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 day

docs:
  stage: deploy
  tags:
    - static-server
  dependencies:
    - test
  script:
    - rm -rf /srv/coverage.gitlab.ccel.org/htdocs/hyphenator
    - mv htmlcov/ /srv/coverage.gitlab.ccel.org/htdocs/hyphenator
  only:
    - master
