tests:
  stage: test
  tags:
    - python
  script:
    - pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt
    - pycodestyle .
    - python3 -c "import nltk; nltk.download('cmudict')"
    - pytest tests --cov=hyphenator --cov-report term --cov-report html
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 day
docs:
  stage: deploy
  tags:
    - static-server
  dependencies:
    - tests
  script:
    - rm -rf /srv/coverage.gitlab.ccel.org/htdocs/hyphenator
    - mv htmlcov/ /srv/coverage.gitlab.ccel.org/htdocs/hyphenator
  only:
    - master
